---
- name: Generate locales
  ansible.builtin.command:
    cmd: /usr/bin/locale-gen
  listen: Generate locales

- name: Restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd.service
    state: restarted
  listen: Restart systemd-networkd

- name: restart bluetooth
  ansible.builtin.systemd:
    name: bluetooth.service
    state: restarted
  listen: restart bluetooth
  when: ansible_service_mgr == 'systemd'
