---
- name: Generate locales
  ansible.builtin.command:
    cmd: /usr/bin/locale-gen
  listen: Generate locales

- name: Restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd.service
    state: restarted
  listen: Restart systemd-networkd
